excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  
disabled_rules:
  - force_cast
  - colon
  - switch_case_alignment
  - redundant_string_enum_value
  - closure_parameter_position
line_length: 140
